export {default as logo} from './logo.svg'
export {default as company} from './suitcase.svg'
export {default as product} from './apps-svgrepo-com.svg'
export {default as community} from './group-of-people-having-a-conversation-svgrepo-com.svg'
export {default as translate} from './translate-svgrepo-com.svg'